CREATE DATABASE IF NOT EXISTS jetstox;
USE jetstox;

SET foreign_key_checks = 0;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Stocks;
DROP TABLE IF EXISTS Profiles;
DROP TABLE IF EXISTS PaperPortfolios;
SET foreign_key_checks = 1;

CREATE TABLE IF NOT EXISTS Users (
    email VARCHAR(120),
    password VARCHAR(120),
    PRIMARY KEY (email)
) ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS Stocks(
    symbol VARCHAR(120),
    name VARCHAR(120),
    PRIMARY KEY (symbol)
) ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS Profiles(
    email VARCHAR(120),
    name VARCHAR(120),
    secq1 VARCHAR(120),
    secq2 VARCHAR(120),
    seca1 VARCHAR(120),
    seca2 VARCHAR(120),
    PRIMARY KEY (email),
    FOREIGN KEY (email) REFERENCES Users(email) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB;
CREATE TABLE IF NOT EXISTS PaperPortfolios(
    email VARCHAR(120),
    symbol VARCHAR(120),
    amount INT,
    PRIMARY KEY (email, symbol),
    FOREIGN KEY (email) REFERENCES Users(email) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (symbol) REFERENCES Stocks(symbol) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB;
